# AUTOGENERATED! DO NOT EDIT! File to edit: 06_messenger.ipynb (unless otherwise specified).

__all__ = ['get_info', 'login']

# Cell
from functools import lru_cache
# maxsize=1: 只能暫存一組帳號紀錄
@lru_cache(maxsize=1)
def get_info(reset=False):
    # if user doesn't want to re-enter info
    # and one has enter login before this program is exited
    # if user wants to re-enter his/hers info:
    #   clear the previous entered record
    if reset == True:
        print("clear previous entered info")
        get_info.cache_clear()
    # if the user has entered account info
    if get_info.cache_info().hits > 0:
        print("hits: %d; entered, return" % get_info.cache_info().hits)
        return
    # else, enter the info
    return input("account: "), input("password: ")


# Cell
# Attention: it'll automatically logout when this function is over
def login(reset=False, cb_list=[]):
    usr, pwd = get_info(reset=reset)
    from selenium import webdriver
    from webdriver_manager.chrome import ChromeDriverManager
    from time import sleep
    driver = webdriver.Chrome(ChromeDriverManager().install())
    driver.get('https://www.facebook.com/')
    print ("Opened facebook")
    sleep(1)

    username_box = driver.find_element('id','email')
    username_box.send_keys(usr)
    print ("Email Id entered")
    sleep(1)

    password_box = driver.find_element('id','pass')
    password_box.send_keys(pwd)
    print ("Password entered")

    login_box = driver.find_element('name','login')
    login_box.click()
    print ("Login Done")
    sleep(1)
    # loop through cb_list here
    # cb_list: list of name of the functions to be executed:
    # aka, a list of string
    # e.g., download conversation, ....
    for ele in cb_list:
        #TODO how do we call function via string
        # since directly input functions
        pass
    return True
