# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"write_fetch_result": "02_fetch_emoji.ipynb",
         "fetch_emoji": "02_fetch_emoji.ipynb",
         "list_out_existing_filenames_of_plurks": "02_fetch_emoji.ipynb"}

modules = ["fetch_emoji.py"]

doc_url = "https://Kelvinthedrugger.github.io/plurk/"

git_url = "https://github.com/Kelvinthedrugger/plurk/tree/main/"

def custom_doc_links(name): return None
